
function main(a){
	try{
	
	}
	catch(Exception e){
		print("hello"+19);
	}
	print("hello"+19);
}
